spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: letmein
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true

server:
  servlet:
    context-path: /bank
