spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/debit_credit
    username: postgres
    password: letmein
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true

server:
  servlet:
    context-path: /debit-credit

### Pessimistic locking
#transaction:
#  lock-mode: pessimistic  # pessimistic | optimistic
#async:
#  enabled: false

### Optimistic locking
#transaction:
#  lock-mode: optimistic  # pessimistic | optimistic
#async:
#  enabled: false

### Sharded processing with optimistic locking
transaction:
  lock-mode: optimistic  # pessimistic | optimistic
async:
  enabled: true
  shards: 25

